(function (angular) {
    'use strict';

    angular.module('categories.mock', [])
        .constant("categoriesConstant", [{
            "id": 0,
            "name": "Mathematics",
            "shortName": "M",
            "parentId": null,
            "typeId": 101,
            "instruction": null,
            "weight": null,
            "subScore1Id": null,
            "subScore2Id": null
        },
            {
                "id": 7,
                "name": "Verbal ",
                "shortName": "V",
                "parentId": null,
                "typeId": 101,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 8,
                "name": "Essay",
                "shortName": "E",
                "parentId": null,
                "typeId": 101,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 9,
                "name": "Mathematics",
                "shortName": "MA",
                "parentId": 0,
                "typeId": 102,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 10,
                "name": "Reading ",
                "shortName": "RE",
                "parentId": 7,
                "typeId": 102,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 11,
                "name": "Writing",
                "shortName": "WT",
                "parentId": 7,
                "typeId": 102,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 12,
                "name": "Essay",
                "shortName": "ES",
                "parentId": 8,
                "typeId": 102,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 13,
                "name": "Intermediate Algebra",
                "shortName": "IA",
                "parentId": 9,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 14,
                "name": "Numbers & Operations",
                "shortName": "NO",
                "parentId": 9,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 15,
                "name": "Coordinate Geometry",
                "shortName": "CG",
                "parentId": 9,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 16,
                "name": "Plane Geometry",
                "shortName": "PG",
                "parentId": 9,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 17,
                "name": "Solving Equations/Word problems",
                "shortName": "SW",
                "parentId": 9,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 18,
                "name": "Trigonometry",
                "shortName": "TR",
                "parentId": 9,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 19,
                "name": "Info and Ideas",
                "shortName": "II",
                "parentId": 10,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 20,
                "name": "Rhetoric",
                "shortName": "RH",
                "parentId": 10,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 21,
                "name": "Synthesis",
                "shortName": "SY",
                "parentId": 10,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 22,
                "name": "Evidence",
                "shortName": "EV",
                "parentId": 11,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 23,
                "name": "Word Choice",
                "shortName": "WO",
                "parentId": 11,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 24,
                "name": "Organization",
                "shortName": "OR",
                "parentId": 11,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 25,
                "name": "Sentence Strutuce",
                "shortName": "SS",
                "parentId": 11,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 26,
                "name": "Conventions of Usage",
                "shortName": "CU",
                "parentId": 11,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 27,
                "name": "Punctuation",
                "shortName": "PU",
                "parentId": 11,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 28,
                "name": "Reading",
                "shortName": "RE",
                "parentId": 12,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 29,
                "name": "Analysis",
                "shortName": "AN",
                "parentId": 12,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 30,
                "name": "Writing",
                "shortName": "WR",
                "parentId": 12,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 31,
                "name": "Quantative Evaluation",
                "shortName": "TE",
                "parentId": 12,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 32,
                "name": "Qualatative Evaluation",
                "shortName": "LE",
                "parentId": 12,
                "typeId": 103,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 33,
                "name": "Complex Numbers",
                "shortName": "CPLX",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 34,
                "name": "Direct and inverse variation",
                "shortName": "DAIV",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 35,
                "name": "English to Math",
                "shortName": "ETOM",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 36,
                "name": "Exponential Growth and Decay",
                "shortName": "EXGD",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 37,
                "name": "Composite Functions",
                "shortName": "FCMP",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 38,
                "name": "Evaluating Functions",
                "shortName": "FEVA",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 39,
                "name": "Linear Functions",
                "shortName": "FLIN",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 40,
                "name": "Functions as Models",
                "shortName": "FMOD",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 41,
                "name": "Polynomial Functions",
                "shortName": "FPLY",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 42,
                "name": "Quadratic Functions",
                "shortName": "FQDR",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 43,
                "name": "Qualitative Behavior of Functions",
                "shortName": "FQLT",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 44,
                "name": "Inequalities",
                "shortName": "INEQ",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 45,
                "name": "Polynomial Division",
                "shortName": "PDIV",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 46,
                "name": "Ratios and Proportions",
                "shortName": "RATE",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 47,
                "name": "Sequences",
                "shortName": "SEQS",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 48,
                "name": "Slopes, parallel lines, and perpendicular lines",
                "shortName": "SLPS",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 49,
                "name": "Systems of linear equations and inequalities",
                "shortName": "SYSE",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 50,
                "name": "Mean/Median/Mode",
                "shortName": "AVGS",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 51,
                "name": "Complex Data interpretation",
                "shortName": "DATC",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 52,
                "name": "Simple Data interpretation",
                "shortName": "DATS",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 53,
                "name": "Elementary Number Theory",
                "shortName": "ENTH",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 54,
                "name": "Expression Manipulation",
                "shortName": "EXPM",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 55,
                "name": "Exponents",
                "shortName": "EXPO",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 56,
                "name": "Fractions and rational numbers",
                "shortName": "FRAC",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 57,
                "name": "Math to English",
                "shortName": "MTOE",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 58,
                "name": "Percents",
                "shortName": "PERC",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 59,
                "name": "Probability",
                "shortName": "PROB",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 60,
                "name": "Statistical analysis, standard deviation",
                "shortName": "STAT",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 61,
                "name": "Two-Way Tables",
                "shortName": "TWMT",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 62,
                "name": "Unit Conversion",
                "shortName": "UNIT",
                "parentId": 14,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 1,
                "subScore2Id": null
            },
            {
                "id": 63,
                "name": "Distance Formula",
                "shortName": "DISF",
                "parentId": 15,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 64,
                "name": "Angles in the plane",
                "shortName": "ANGL",
                "parentId": 16,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 65,
                "name": "Circles",
                "shortName": "CIRC",
                "parentId": 16,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 66,
                "name": "Dimension Shifts",
                "shortName": "DIMS",
                "parentId": 16,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 67,
                "name": "Polygons with more than 4 sides",
                "shortName": "POLY",
                "parentId": 16,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 68,
                "name": "Solid geometry",
                "shortName": "SLID",
                "parentId": 16,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 69,
                "name": "Triangles",
                "shortName": "TRIS",
                "parentId": 16,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 70,
                "name": "Solving quadratic equations by factoring",
                "shortName": "QUAD",
                "parentId": 17,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 2,
                "subScore2Id": null
            },
            {
                "id": 71,
                "name": "Solving equations",
                "shortName": "SOLV",
                "parentId": 17,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 0,
                "subScore2Id": null
            },
            {
                "id": 72,
                "name": "Trigonometry",
                "shortName": "TRIG",
                "parentId": 18,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 73,
                "name": "Explicit Detail",
                "shortName": "DETA",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 74,
                "name": "Implication",
                "shortName": "IMPL",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 75,
                "name": "New Context",
                "shortName": "NEWC",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 76,
                "name": "Citing Textual Evidence",
                "shortName": "CTEV",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 6,
                "subScore2Id": null
            },
            {
                "id": 77,
                "name": "Main Idea",
                "shortName": "MAIN",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 78,
                "name": "Themes",
                "shortName": "THME",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 79,
                "name": "Summarizing",
                "shortName": "SUMM",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 80,
                "name": "Cause/Effect",
                "shortName": "CSEF",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 81,
                "name": "Compare/Contrast",
                "shortName": "COMP",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 82,
                "name": "Sequence",
                "shortName": "SEQU",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 83,
                "name": "Words In Context",
                "shortName": "WICT",
                "parentId": 19,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 5,
                "subScore2Id": null
            },
            {
                "id": 84,
                "name": "Word Choice",
                "shortName": "WRDC",
                "parentId": 20,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 5,
                "subScore2Id": null
            },
            {
                "id": 85,
                "name": "Text Structure",
                "shortName": "TEXT",
                "parentId": 20,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 6,
                "subScore2Id": null
            },
            {
                "id": 86,
                "name": "Point of View",
                "shortName": "POVW",
                "parentId": 20,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 87,
                "name": "Purpose",
                "shortName": "PURP",
                "parentId": 20,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 88,
                "name": "Arguments",
                "shortName": "ARGU",
                "parentId": 20,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 89,
                "name": "Multiple Texts",
                "shortName": "MULT",
                "parentId": 21,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 90,
                "name": "Information",
                "shortName": "INFO",
                "parentId": 21,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 91,
                "name": "Conclusions",
                "shortName": "CNCL",
                "parentId": 21,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 92,
                "name": "Connections",
                "shortName": "CONN",
                "parentId": 21,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 93,
                "name": "Proposition",
                "shortName": "PROP",
                "parentId": 22,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 6,
                "subScore2Id": 3
            },
            {
                "id": 94,
                "name": "Supporting",
                "shortName": "SUPP",
                "parentId": 22,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 6,
                "subScore2Id": 3
            },
            {
                "id": 95,
                "name": "Focus",
                "shortName": "FOCU",
                "parentId": 22,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 6,
                "subScore2Id": 3
            },
            {
                "id": 96,
                "name": "Quantitative Information",
                "shortName": "QUAN",
                "parentId": 22,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 6,
                "subScore2Id": 3
            },
            {
                "id": 97,
                "name": "Precision",
                "shortName": "PREC",
                "parentId": 23,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 5,
                "subScore2Id": 4
            },
            {
                "id": 98,
                "name": "Concision",
                "shortName": "CONC",
                "parentId": 23,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 5,
                "subScore2Id": 4
            },
            {
                "id": 99,
                "name": "Style and Tone",
                "shortName": "TONE",
                "parentId": 23,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 5,
                "subScore2Id": 4
            },
            {
                "id": 100,
                "name": "Syntax",
                "shortName": "SYNT",
                "parentId": 23,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": 5,
                "subScore2Id": 4
            },
            {
                "id": 101,
                "name": "Logical Sequence",
                "shortName": "LOSE",
                "parentId": 24,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 3
            },
            {
                "id": 102,
                "name": "Introductions",
                "shortName": "INTR",
                "parentId": 24,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 3
            },
            {
                "id": 103,
                "name": "Transitions",
                "shortName": "TRAN",
                "parentId": 24,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 3
            },
            {
                "id": 104,
                "name": "Conclusion",
                "shortName": "CONL",
                "parentId": 24,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 3
            },
            {
                "id": 105,
                "name": "Sentence Formation",
                "shortName": "SEFO",
                "parentId": 25,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 106,
                "name": "Shifts",
                "shortName": "SHIF",
                "parentId": 25,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 107,
                "name": "Possessive Determiners",
                "shortName": "POSD",
                "parentId": 26,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 108,
                "name": "Agreement",
                "shortName": "AGRE",
                "parentId": 26,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 109,
                "name": "Diction",
                "shortName": "DICT",
                "parentId": 26,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 110,
                "name": "Idiom",
                "shortName": "IDIO",
                "parentId": 26,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 111,
                "name": "Sentence Punctuation",
                "shortName": "PUNC",
                "parentId": 27,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 112,
                "name": "Possessive Nouns and Pronouns",
                "shortName": "POSN",
                "parentId": 27,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 113,
                "name": "Comma in a series",
                "shortName": "CSER",
                "parentId": 27,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 114,
                "name": "Comma- Non Essential",
                "shortName": "CNON",
                "parentId": 27,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 115,
                "name": "Parentheses- Non Essential",
                "shortName": "PNON",
                "parentId": 27,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": 4
            },
            {
                "id": 116,
                "name": "Central Idea",
                "shortName": "CENT",
                "parentId": 28,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 117,
                "name": "Importance Detail",
                "shortName": "IMPO",
                "parentId": 28,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 118,
                "name": "Evidence",
                "shortName": "EVID",
                "parentId": 29,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 119,
                "name": "Reasoning",
                "shortName": "REAS",
                "parentId": 29,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 120,
                "name": "Persuasive Elements",
                "shortName": "PERS",
                "parentId": 29,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 121,
                "name": "Sentence Placement",
                "shortName": "SPLA",
                "parentId": 30,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 122,
                "name": "Sentence Revision",
                "shortName": "SREV",
                "parentId": 30,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 123,
                "name": "Organization",
                "shortName": "EORG",
                "parentId": 31,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 124,
                "name": "Use of Language",
                "shortName": "ELAN",
                "parentId": 31,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 125,
                "name": "Ideas and Analysis",
                "shortName": "EANA",
                "parentId": 31,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 126,
                "name": "Essay Thesis Statements",
                "shortName": "ETHE",
                "parentId": 32,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 127,
                "name": "Essay Introductions",
                "shortName": "EINT",
                "parentId": 32,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 128,
                "name": "Essay Body Paragraphs",
                "shortName": "EBOD",
                "parentId": 32,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 129,
                "name": "Essay Conclusions",
                "shortName": "ECON",
                "parentId": 32,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            },
            {
                "id": 179,
                "name": "Absolute Value",
                "shortName": "ABSV",
                "parentId": 13,
                "typeId": 104,
                "instruction": null,
                "weight": null,
                "subScore1Id": null,
                "subScore2Id": null
            }
        ]);
})(angular);
