(function (angular) {
    'use strict';

    angular.module('znk.infra', [
        'znk.infra.analytics',
        'znk.infra.assignModule',
        'znk.infra.auth',
        'znk.infra.autofocus',
        'znk.infra.config',
        'znk.infra.content',
        'znk.infra.contentAvail',
        'znk.infra.deviceNotSupported',
        'znk.infra.enum',
        'znk.infra.estimatedScore',
        'znk.infra.exams',
        'znk.infra.exerciseDataGetters',
        'znk.infra.exerciseResult',
        'znk.infra.exerciseUtility',
        'znk.infra.filters',
        'znk.infra.general',
        'znk.infra.hint',
        'znk.infra.moduleResults',
        'znk.infra.personalization',
        'znk.infra.pngSequence',
        'znk.infra.popUp',
        'znk.infra.presence',
        'znk.infra.scoring',
        'znk.infra.scroll',
        'znk.infra.sharedScss',
        'znk.infra.stats',
        'znk.infra.storage',
        'znk.infra.svgIcon',
        'znk.infra.user',
        'znk.infra.userSession',
        'znk.infra.utility',
        'znk.infra.znkAudioPlayer',
        'znk.infra.znkExercise',
        'znk.infra.znkModule',
        'znk.infra.znkTimeline'
    ]);
})(angular);
